#!/bin/sh

export DVTM_STATUS_FIFO="/tmp/dvtm-status.$$"

[ -p "$DVTM_STATUS_FIFO" ] || mkfifo -m 600 "$DVTM_STATUS_FIFO" || exit 1

export SHELL=/usr/local/bin/zsh
export TERMINFO_DIRS=/usr/share/terminfo:/usr/local/share/terminfo
export DVTM_EDITOR=/usr/bin/less
/usr/local/bin/dvtm -s "$DVTM_STATUS_FIFO" "$@" 2> /dev/null
rm -f "$DVTM_STATUS_FIFO"
