#!/bin/sh
xmodmap ~/.xmodmap
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources
sh ~/.fehbg
xrandr --output VGA1 --preferred --primary --output HDMI1 --preferred --right-of VGA1
xset s 180
firefox &
thunderbird &
hexchat &
ssh-add </dev/null
~/.dotfiles/status.sh &
export SHELL=/usr/bin/zsh
export _JAVA_AWT_WM_NONREPARENTING=1
urxvtd -q -f -o
exec ~/.dotfiles/continuous-dwm
