#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
export WINIT_HIDPI_FACTOR=1.0
export WINIT_X11_SCALE_FACTOR=1.0

eval "$(dbus-launch --exit-with-x11 --sh-syntax)"

xinput set-prop "DLL075B:01 06CB:76AF Touchpad" "libinput Tapping Enabled" 1

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

if [ -x ~/.xrandr ]; then
	~/.xrandr
	if which srandrd >/dev/null 2>&1; then
		srandrd $HOME/.xrandr
	fi
fi

if [ -x ~/.xkbmap ]; then
	~/.xkbmap
	if which xinputd >/dev/null 2>&1; then
		xinputd $HOME/.xkbmap
	fi
fi

eval $(gnome-keyring-daemon --components=secrets --start)
eval $(ssh-agent)
($HOME/src/dwmstatus/target/release/dwmstatus; xsetroot -name "dwmstatus crashed") &
dunst &

xset s 300
xset dpms 300
xss-lock -- ${HOME}/.screenlock &

firefox &
thunderbird &
hexchat &
which slack >/dev/null 2>&1 && slack &
which nextcloud >/dev/null 2>&1 && nextcloud --background &

exec dwm
