#!/bin/sh

xinput set-prop "DLL075B:01 06CB:76AF Touchpad" "libinput Tapping Enabled" 1

setxkbmap -option "caps:swapescape"

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources
if [ -f ~/.xrandr ]; then
	~/.xrandr
	if which srandrd >/dev/null 2>&1; then
		srandrd $HOME/.xrandr
	fi
fi

export _JAVA_AWT_WM_NONREPARENTING=1
export WINIT_HIDPI_FACTOR=1.0

eval $(ssh-agent)
($HOME/src/dwmstatus/target/release/dwmstatus; xsetroot -name "dwmstatus crashed") &
dunst &

xset s 300
xset dpms 300
xss-lock -- sxlock -f '-*-dejavu sans-*-*-*-*-*-*-*-*-*-*-*-*' &

firefox &
thunderbird &
hexchat &
which hipchat4 >/dev/null 2>&1 && hipchat4 &

exec dwm
