# -*- mode: sh -*-

typeset -U path PATH

# Autopaths
path_dirs=(
    "/usr/local/go/bin"
    "$HOME/.poetry/bin"
    "$HOME/.local/share/node_modules/bin"
)
for path_dir in "$path_dirs[@]"; do
    if [ -d "$path_dir" ]; then
        path+="$path_dir"
    fi
done

# Autosources
source_scripts=(
    "$HOME/miniconda3/etc/profile.d/conda.sh"
    "$HOME/miniforge3/etc/profile.d/conda.sh"
    "$HOME/mambaforge/etc/profile.d/conda.sh"
    "$HOME/.cargo/env"
)
for source_script in "$source_scripts[@]"; do
    if [ -f "$source_script" ]; then
        . "$source_script"
    fi
done

# Local ruby install
if [ -d "${RBENV_ROOT:=$HOME/.rbenv}" ]; then
    path=("${RBENV_ROOT}/bin" $path)
    eval "$(rbenv init -)"
fi

# Local perl install
if [ -d "$HOME/perl5" ]; then
    eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
fi

# Go path
if [ -d "${HOME}/go" ]; then
    export GOPATH="${HOME}/go"
    path+="${GOPATH}/bin"
fi

# Local pyenv install
if [ -d "${PYENV_ROOT:=${HOME}/.pyenv}" ]; then
    export PYENV_ROOT
    path=("${PYENV_ROOT}/bin" $path)
    eval "$(pyenv init --path)";
fi

# Local executables
path=("$HOME/.local/bin" $path)

# Default colorscheme
if [ -z "$LC_COLORSCHEME_VARIANT" ]; then
    export LC_COLORSCHEME_VARIANT=__COLORSCHEME_VARIANT__
fi

# Cookiecutter config path
if [ -f "$HOME/.config/cookiecutter/cookiecutter.yaml" ]; then
    export COOKIECUTTER_CONFIG="$HOME/.config/cookiecutter/cookiecutter.yaml"
fi
