# -*- mode: sh -*-

if [ "$TERM" = "tramp" ]; then
    unsetopt zle
    PS1='$ '
    return
fi

zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit

source ~/.fresh/build/shell.sh
source ~/.fresh/build/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

fpath=(~/.fresh/build/completion $fpath)

if [[ "$SSH_CONNECTION" = "" ]]; then
    source ~/.fresh/build/colors/base16-solarized-${LC_COLORSCHEME_VARIANT}.sh
fi

HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt append_history
setopt share_history
bindkey -e

bindkey ';5D' backward-word
bindkey ';5C' forward-word

setopt correct

export FZF_MARKS_FILE=${XDG_CONFIG_HOME:-${HOME}/.config}/fzf-marks/bookmarks

if command -v exa >/dev/null; then
    alias ls=exa
fi

if command -v pscp >/dev/null; then
    alias scp="pscp -sftp -P 22"
fi

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

export EDITOR="$(command -v vim)"
export PARALLEL_SHELL=/bin/sh

alias bd='. bd -s'

gitignore-std () {
    echo '#' $1 >>.gitignore
    cat ~/.fresh/source/github/gitignore/$1 >>.gitignore
    git add .gitignore
    git commit -m "Add standard ignore $1"
}
