# -*- mode: sh -*-

if [ "$TERM" = "tramp" ]; then
    unsetopt zle
    PS1='$ '
    return
fi

source ~/.fresh/build/shell.sh
source ~/.fresh/build/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

fpath=(~/.fresh/build/completion $fpath)

source ~/.fresh/build/colors/base16-solarized-${LC_COLORSCHEME_VARIANT}.sh

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'
zstyle :compinstall filename '/home/gmacon/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt append_history
setopt share_history
bindkey -e
# End of lines configured by zsh-newuser-install

bindkey ';5D' backward-word
bindkey ';5C' forward-word

setopt correct

export FZF_MARKS_FILE=${XDG_CONFIG_HOME:-${HOME}/.config}/fzf-marks/bookmarks

if command -v exa >/dev/null; then
    alias ls=exa
fi

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

export EDITOR="$(command -v vim)"

alias bd='. bd -s'

gitignore-std () {
    echo '#' $1 >>.gitignore
    cat ~/.fresh/source/github/gitignore/$1 >>.gitignore
    git add .gitignore
    git commit -m "Add standard ignore $1"
}
